/**
 * Contract check: feeds responses produced by the real FastAPI routers (captured by
 * backend/tests/test_api_*.py into backend/tests/samples/) through the frontend's
 * adapters. Fails if the backend and the UI disagree about field names or types.
 *
 *   cd backend && python3 -m pytest tests -q && cd ../frontend && npm run contract
 */
import { existsSync, readFileSync, readdirSync } from "node:fs";
import path from "node:path";
import * as A from "../src/services/api/adapters";

const DIR = path.resolve(import.meta.dirname, "../../backend/tests/samples");
const checks: Record<string, (body: never) => string[]> = {
  "home.json": (body) => {
    const h = A.toHome(body);
    const errs: string[] = [];
    if (!(h.readiness.score >= 0 && h.readiness.score <= 100)) errs.push("readiness score out of range");
    if (!h.readiness.reason.hi) errs.push("missing Hindi readiness reason");
    if (!h.kpis) errs.push("kpis missing");
    if (h.trend.length !== 30 || h.trend.some((t) => t.fraud == null)) errs.push("trend must be 30 days with confirmed_fraud");
    if (!h.attention.length || h.attention.some((a) => !a.kind || !a.entityId)) errs.push("attention items malformed");
    if (h.attention.some((a) => (a.kind === "report_overdue" || a.kind === "report_due") && (!a.dueAt || !a.name?.en))) errs.push("report items need due_at and name");
    if (!h.brief?.text.en || !h.brief.text.hi) errs.push("weekly brief missing a language");
    if (!h.asOf) errs.push("as_of missing");
    return errs;
  },
  "alerts.json": (body) => {
    const pg = A.toAlertPage(body);
    const errs: string[] = [];
    if (!pg.alerts.length) errs.push("no alerts");
    for (const a of pg.alerts) {
      if (!a.dueAt || Number.isNaN(Date.parse(a.dueAt))) errs.push(`${a.id}: due_at missing or unparseable`);
      if (!(a.riskLevel >= 1 && a.riskLevel <= 5)) errs.push(`${a.id}: risk_level out of range`);
      if (!a.customerName.en) errs.push(`${a.id}: no display name`);
    }
    if (!pg.alerts.some((a) => a.amount != null && a.txnCount != null)) errs.push("no alert carries amount_inr/txn_count");
    if (!pg.alerts.some((a) => a.reportFiled)) errs.push("str_filed never true in sample");
    return errs;
  },
  "alert_detail.json": (body) => checkDetail(body, true),
  "rings.json": (body) => {
    const errs: string[] = [];
    const rings = (body as { rings: never[] }).rings.map(A.toRing);
    if (!rings.length) errs.push("no rings");
    for (const r of rings) {
      if (!r.name.en || !r.name.hi) errs.push(`${r.id}: name missing a language`);
      if (!r.confidence || r.speedHours == null || !r.city) errs.push(`${r.id}: confidence/speed/city missing`);
    }
    return errs;
  },
  "ring_detail.json": (body) => {
    const d = A.toRingDetail(body);
    const errs: string[] = [];
    if (!d.graph.nodes.every((n) => n.role && n.moneyIn != null)) errs.push("members need role and money in/out");
    if (!d.graph.edges.some((e) => e.kind === "sent_money" && e.amount != null)) errs.push("money edges need amounts");
    if (!d.transactions.length) errs.push("no transfers");
    return errs;
  },
  "rules.json": (body) => {
    const errs: string[] = [];
    for (const r of (body as { rules: never[] }).rules.map(A.toRule)) {
      if (!r.plain?.en || !r.plain.hi) errs.push(`${r.id}: plain text missing a language`);
      if (!r.citation || !r.sourceQuote) errs.push(`${r.id}: citation/source missing`);
      if (r.highlight && !r.sourceQuote?.includes(r.highlight)) errs.push(`${r.id}: highlight not in source`);
    }
    return errs;
  },
  "conflicts.json": (body) => {
    const cs = (body as { conflicts: never[] }).conflicts.map(A.toConflict);
    return cs.length && cs.every((c) => c.a.clauseText && c.b.plain && (c.kind === "overlap" || c.kind === "contradiction")) ? [] : ["conflicts malformed"];
  },
  "rule_health.json": (body) => {
    const h = A.toRuleHealth(body);
    return h.rows.length && h.rows.every((r) => ["healthy", "noisy", "quiet"].includes(r.verdict)) ? [] : ["health rows malformed"];
  },
  "job.json": (body) => {
    const j = A.toJob(body);
    return j.step === 4 && j.ruleIds.length && j.circularNo ? [] : ["completed job needs step 4, rule ids and circular"];
  },
  "tm_rules.json": (body) => {
    const ts = (body as { rules: never[] }).rules.map(A.toTunable);
    return ts.length && ts.every((x) => x.param.min < x.param.max && x.param.value >= x.param.min && x.param.label.hi) ? [] : ["tunable params malformed"];
  },
  "replay.json": (body) => {
    const r = A.toReplay(body);
    return r.current.alerts >= 0 && r.proposed.fraudCaught <= r.fraudTotal && r.days > 0 ? [] : ["replay malformed"];
  },
  /** Captured from live Snowflake (not regenerated by pytest); the live ring tables are nearly empty. */
  "alert_detail_live.json": (body) => checkDetail(body, false),
};

function checkDetail(body: never, needsConnections: boolean): string[] {
  {
    const d = A.toAlertDetail(body);
    const errs: string[] = [];
    if (needsConnections && !d.story) errs.push("story preamble not cleaned or missing");
    if (!d.reasons.length || d.reasons.some((r) => !r.text.en || !r.text.hi || !(r.weight > 0))) errs.push("reasons malformed");
    if (!d.timeline.length || d.timeline.some((e) => !e.title.en || Number.isNaN(Date.parse(e.at)))) errs.push("timeline malformed");
    if (!d.transactions.every((t) => t.direction === "CREDIT" || t.direction === "DEBIT")) errs.push("transaction direction");
    if (needsConnections && (!d.connections || d.connections.nodes[0]?.kind !== "subject")) errs.push("connections missing subject");
    if (!d.citation?.highlight) errs.push("citation_ref.highlight missing");
    return errs;
  }
}

let failed = 0;
if (!existsSync(DIR)) {
  console.error(`No samples at ${DIR}. Run the backend tests first.`);
  process.exit(1);
}
for (const file of readdirSync(DIR).filter((f) => f.endsWith(".json"))) {
  const check = checks[file];
  if (!check) {
    console.log(`·  ${file}: no check defined`);
    continue;
  }
  const errs = check(JSON.parse(readFileSync(path.join(DIR, file), "utf8")) as never);
  if (errs.length) {
    failed++;
    console.error(`✗  ${file}\n   - ${errs.join("\n   - ")}`);
  } else console.log(`✓  ${file}`);
}
process.exit(failed ? 1 : 0);
