-- =============================================================================
-- KAVACH Phase 2C: CORE Tables (CTAS from RAW, typed, tagged, policies)
-- =============================================================================
USE ROLE ACCOUNTADMIN;
USE DATABASE KAVACH_DB;
USE WAREHOUSE KAVACH_WH;

-- =========================================================================
-- 1. CORE tables created from RAW
-- =========================================================================
CREATE OR REPLACE TABLE CORE.CUSTOMERS AS
SELECT CUSTOMER_ID, CUSTOMER_NAME, PAN, DOB::DATE AS DOB,
    CITY, STATE, STATE_CODE, REGION, OCCUPATION, DECLARED_ANNUAL_INCOME,
    KYC_STATUS, KYC_LAST_UPDATED::DATE AS KYC_LAST_UPDATED,
    RISK_CATEGORY, IS_PEP, ONBOARDING_CHANNEL, SEGMENT
FROM RAW.CUSTOMERS;

CREATE OR REPLACE TABLE CORE.ACCOUNTS AS
SELECT ACCOUNT_ID, CUSTOMER_ID, ACCOUNT_TYPE, OPEN_DATE::DATE AS OPEN_DATE,
    BRANCH_CODE, STATUS, AVG_MONTHLY_BALANCE
FROM RAW.ACCOUNTS;

CREATE OR REPLACE TABLE CORE.TRANSACTIONS AS
SELECT TXN_ID, ACCOUNT_ID, TXN_TS::TIMESTAMP_NTZ AS TXN_TS,
    AMOUNT_INR, CHANNEL, DIRECTION, COUNTERPARTY, COUNTERPARTY_BANK,
    COUNTRY, MERCHANT_CATEGORY, NARRATION, DEVICE_ID, IP_ADDRESS
FROM RAW.TRANSACTIONS;

CREATE OR REPLACE TABLE CORE.DEVICES AS
SELECT DEVICE_ID, DEVICE_TYPE, OS, IP_ADDRESS, CITY, COUNTRY_CODE,
    FIRST_SEEN::DATE AS FIRST_SEEN, ACCOUNT_ID
FROM RAW.DEVICES;

CREATE OR REPLACE TABLE CORE.LOGINS AS
SELECT LOGIN_ID, ACCOUNT_ID, DEVICE_ID, IP_ADDRESS,
    LOGIN_TS, CITY, COUNTRY, SUCCESS
FROM RAW.LOGINS;

CREATE OR REPLACE TABLE CORE.BENEFICIARIES AS
SELECT BENEFICIARY_ID, ACCOUNT_ID, BENEFICIARY_ACCOUNT, BENEFICIARY_VPA,
    BENEFICIARY_BANK, BENEFICIARY_NAME, ADDED_AT::TIMESTAMP_NTZ AS ADDED_AT
FROM RAW.BENEFICIARIES;

-- =========================================================================
-- 2. PII tags and masking policies
-- =========================================================================
ALTER TABLE CORE.CUSTOMERS ALTER COLUMN PAN
    SET TAG CORE.PII_LEVEL = 'HIGH';
ALTER TABLE CORE.CUSTOMERS ALTER COLUMN CUSTOMER_NAME
    SET MASKING POLICY CORE.mask_customer_name;
ALTER TABLE CORE.CUSTOMERS
    ADD ROW ACCESS POLICY CORE.rap_region_filter ON (REGION);

-- DATA_DOMAIN tags
ALTER TABLE CORE.CUSTOMERS    SET TAG CORE.DATA_DOMAIN = 'CUSTOMER';
ALTER TABLE CORE.ACCOUNTS     SET TAG CORE.DATA_DOMAIN = 'ACCOUNT';
ALTER TABLE CORE.TRANSACTIONS SET TAG CORE.DATA_DOMAIN = 'TRANSACTION';
ALTER TABLE CORE.DEVICES      SET TAG CORE.DATA_DOMAIN = 'CUSTOMER';
ALTER TABLE CORE.LOGINS       SET TAG CORE.DATA_DOMAIN = 'CUSTOMER';
ALTER TABLE CORE.BENEFICIARIES SET TAG CORE.DATA_DOMAIN = 'ACCOUNT';

-- =========================================================================
-- 3. Grants
-- =========================================================================
GRANT SELECT ON ALL TABLES IN SCHEMA CORE TO ROLE KAVACH_ADMIN;
GRANT SELECT ON ALL TABLES IN SCHEMA CORE TO ROLE KAVACH_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA CORE TO ROLE KAVACH_AUDITOR;
GRANT SELECT ON ALL TABLES IN SCHEMA CORE TO ROLE KAVACH_ANALYST_NORTH;
