-- =============================================================================
-- KAVACH: missing AUDIT table + procedure/function grants
-- =============================================================================
-- Two gaps that only showed up when the API was exercised end to end:
--
-- 1. AUDIT.ALERT_FEEDBACK was live on the original account but never checked
--    into sql/ (it survived only in data/exports/ddl/AUDIT.sql), so
--    POST /api/alerts/{id}/feedback failed with "Table does not exist".
--
-- 2. sql/02_governance.sql grants SELECT on tables/views and USAGE on schemas,
--    but never grants USAGE on PROCEDURES or FUNCTIONS. Everything in AI created
--    by sql/08 and sql/12 therefore had only OWNERSHIP to ACCOUNTADMIN. The
--    backend runs as KAVACH_ADMIN, and Snowflake hides objects a role cannot
--    use, so the failure surfaces as the misleading
--    "Unknown user-defined function AI.BUILD_EVIDENCE_PACK" rather than a
--    permission error. FUTURE grants are included so re-running sql/08 or sql/12
--    does not silently drop access again.
-- =============================================================================
USE ROLE ACCOUNTADMIN;
USE DATABASE KAVACH_DB;
USE WAREHOUSE KAVACH_WH;

CREATE TABLE IF NOT EXISTS KAVACH_DB.AUDIT.ALERT_FEEDBACK (
    FEEDBACK_ID  NUMBER(38,0) AUTOINCREMENT START 1 INCREMENT 1 NOORDER,
    ALERT_ID     VARCHAR NOT NULL,
    RATING       NUMBER(38,0) NOT NULL,
    COMMENT      VARCHAR,
    SUBMITTED_AT TIMESTAMP_NTZ(9) DEFAULT CURRENT_TIMESTAMP()
);

-- Analyst feedback and the activity trail are written through the app.
GRANT SELECT, INSERT ON TABLE KAVACH_DB.AUDIT.ALERT_FEEDBACK TO ROLE KAVACH_ADMIN;
GRANT SELECT, INSERT ON TABLE KAVACH_DB.AUDIT.ALERT_FEEDBACK TO ROLE KAVACH_ANALYST;
GRANT SELECT ON TABLE KAVACH_DB.AUDIT.ALERT_FEEDBACK TO ROLE KAVACH_AUDITOR;
GRANT SELECT ON TABLE KAVACH_DB.AUDIT.ALERT_FEEDBACK TO ROLE KAVACH_REVIEWER;

GRANT INSERT ON TABLE KAVACH_DB.AUDIT.ACTIVITY_LOG    TO ROLE KAVACH_ADMIN;
GRANT INSERT ON TABLE KAVACH_DB.AUDIT.ACTIVITY_LOG    TO ROLE KAVACH_ANALYST;
GRANT INSERT ON TABLE KAVACH_DB.AUDIT.EVIDENCE_REGISTRY TO ROLE KAVACH_ADMIN;
GRANT INSERT ON TABLE KAVACH_DB.AUDIT.EVIDENCE_REGISTRY TO ROLE KAVACH_ANALYST;

-- Procedure / function usage across every project schema.
GRANT USAGE ON ALL PROCEDURES IN SCHEMA KAVACH_DB.AI    TO ROLE KAVACH_ADMIN;
GRANT USAGE ON ALL FUNCTIONS  IN SCHEMA KAVACH_DB.AI    TO ROLE KAVACH_ADMIN;
GRANT USAGE ON ALL PROCEDURES IN SCHEMA KAVACH_DB.RULES TO ROLE KAVACH_ADMIN;
GRANT USAGE ON ALL FUNCTIONS  IN SCHEMA KAVACH_DB.RULES TO ROLE KAVACH_ADMIN;
GRANT USAGE ON ALL PROCEDURES IN SCHEMA KAVACH_DB.CORE  TO ROLE KAVACH_ADMIN;
GRANT USAGE ON ALL FUNCTIONS  IN SCHEMA KAVACH_DB.CORE  TO ROLE KAVACH_ADMIN;
GRANT USAGE ON ALL PROCEDURES IN SCHEMA KAVACH_DB.ML    TO ROLE KAVACH_ADMIN;
GRANT USAGE ON ALL FUNCTIONS  IN SCHEMA KAVACH_DB.ML    TO ROLE KAVACH_ADMIN;
GRANT USAGE ON ALL PROCEDURES IN SCHEMA KAVACH_DB.RAW   TO ROLE KAVACH_ADMIN;
GRANT USAGE ON ALL FUNCTIONS  IN SCHEMA KAVACH_DB.RAW   TO ROLE KAVACH_ADMIN;

GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA KAVACH_DB.AI    TO ROLE KAVACH_ADMIN;
GRANT USAGE ON FUTURE FUNCTIONS  IN SCHEMA KAVACH_DB.AI    TO ROLE KAVACH_ADMIN;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA KAVACH_DB.RULES TO ROLE KAVACH_ADMIN;
GRANT USAGE ON FUTURE FUNCTIONS  IN SCHEMA KAVACH_DB.RULES TO ROLE KAVACH_ADMIN;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA KAVACH_DB.CORE  TO ROLE KAVACH_ADMIN;
GRANT USAGE ON FUTURE FUNCTIONS  IN SCHEMA KAVACH_DB.CORE  TO ROLE KAVACH_ADMIN;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA KAVACH_DB.ML    TO ROLE KAVACH_ADMIN;
GRANT USAGE ON FUTURE FUNCTIONS  IN SCHEMA KAVACH_DB.ML    TO ROLE KAVACH_ADMIN;

-- Read-only personas still need to CALL the explain/evidence paths; the masking
-- policies decide what they actually see, and the API layer returns 403 on the
-- write routes. Denying USAGE here would 500 the page instead of masking it.
GRANT USAGE ON ALL PROCEDURES IN SCHEMA KAVACH_DB.AI TO ROLE KAVACH_ANALYST;
GRANT USAGE ON ALL FUNCTIONS  IN SCHEMA KAVACH_DB.AI TO ROLE KAVACH_ANALYST;
GRANT USAGE ON ALL PROCEDURES IN SCHEMA KAVACH_DB.AI TO ROLE KAVACH_AUDITOR;
GRANT USAGE ON ALL FUNCTIONS  IN SCHEMA KAVACH_DB.AI TO ROLE KAVACH_AUDITOR;
GRANT USAGE ON ALL PROCEDURES IN SCHEMA KAVACH_DB.AI TO ROLE KAVACH_REVIEWER;
GRANT USAGE ON ALL FUNCTIONS  IN SCHEMA KAVACH_DB.AI TO ROLE KAVACH_REVIEWER;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA KAVACH_DB.AI TO ROLE KAVACH_ANALYST;
GRANT USAGE ON FUTURE FUNCTIONS  IN SCHEMA KAVACH_DB.AI TO ROLE KAVACH_ANALYST;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA KAVACH_DB.AI TO ROLE KAVACH_AUDITOR;
GRANT USAGE ON FUTURE FUNCTIONS  IN SCHEMA KAVACH_DB.AI TO ROLE KAVACH_AUDITOR;
GRANT USAGE ON FUTURE PROCEDURES IN SCHEMA KAVACH_DB.AI TO ROLE KAVACH_REVIEWER;
GRANT USAGE ON FUTURE FUNCTIONS  IN SCHEMA KAVACH_DB.AI TO ROLE KAVACH_REVIEWER;

-- The evidence pack is written to and read back from this stage.
GRANT READ, WRITE ON STAGE KAVACH_DB.APP.EVIDENCE_STAGE TO ROLE KAVACH_ADMIN;
GRANT READ, WRITE ON STAGE KAVACH_DB.APP.EVIDENCE_STAGE TO ROLE KAVACH_ANALYST;
GRANT READ ON STAGE KAVACH_DB.APP.EVIDENCE_STAGE TO ROLE KAVACH_AUDITOR;
GRANT READ ON STAGE KAVACH_DB.APP.EVIDENCE_STAGE TO ROLE KAVACH_REVIEWER;

-- =============================================================================
-- VIEW grants
-- =============================================================================
-- sql/02 grants SELECT ON ALL/FUTURE **TABLES** only, which does not cover
-- views. Every view created later (ML.LATEST_RISK_SCORES, ML.EVAL_SCORED, and
-- the AI reporting views) therefore had nothing but OWNERSHIP to ACCOUNTADMIN,
-- and the backend/agent run as KAVACH_ADMIN. Symptom: Ask KAVACH answering
-- "Which are the top 10 risk accounts?" fails on an authorization error for
-- KAVACH_DB.ML.LATEST_RISK_SCORES, because the semantic view sources from it.
--
-- Note also that CREATE OR REPLACE VIEW DROPS existing grants, so anything that
-- recreates these views must re-run this file (or use COPY GRANTS).
GRANT SELECT ON ALL VIEWS IN SCHEMA KAVACH_DB.ML TO ROLE KAVACH_ADMIN;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA KAVACH_DB.ML TO ROLE KAVACH_ADMIN;
GRANT SELECT ON ALL VIEWS IN SCHEMA KAVACH_DB.AI TO ROLE KAVACH_ADMIN;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA KAVACH_DB.AI TO ROLE KAVACH_ADMIN;
GRANT SELECT ON ALL VIEWS IN SCHEMA KAVACH_DB.CORE TO ROLE KAVACH_ADMIN;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA KAVACH_DB.CORE TO ROLE KAVACH_ADMIN;
GRANT SELECT ON ALL VIEWS IN SCHEMA KAVACH_DB.RULES TO ROLE KAVACH_ADMIN;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA KAVACH_DB.RULES TO ROLE KAVACH_ADMIN;
GRANT SELECT ON ALL VIEWS IN SCHEMA KAVACH_DB.REF TO ROLE KAVACH_ADMIN;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA KAVACH_DB.REF TO ROLE KAVACH_ADMIN;
GRANT SELECT ON ALL VIEWS IN SCHEMA KAVACH_DB.APP TO ROLE KAVACH_ADMIN;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA KAVACH_DB.APP TO ROLE KAVACH_ADMIN;
GRANT SELECT ON ALL VIEWS IN SCHEMA KAVACH_DB.AUDIT TO ROLE KAVACH_ADMIN;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA KAVACH_DB.AUDIT TO ROLE KAVACH_ADMIN;
GRANT SELECT ON ALL VIEWS IN SCHEMA KAVACH_DB.ML TO ROLE KAVACH_ANALYST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA KAVACH_DB.ML TO ROLE KAVACH_ANALYST;
GRANT SELECT ON ALL VIEWS IN SCHEMA KAVACH_DB.AI TO ROLE KAVACH_ANALYST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA KAVACH_DB.AI TO ROLE KAVACH_ANALYST;
GRANT SELECT ON ALL VIEWS IN SCHEMA KAVACH_DB.CORE TO ROLE KAVACH_ANALYST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA KAVACH_DB.CORE TO ROLE KAVACH_ANALYST;
GRANT SELECT ON ALL VIEWS IN SCHEMA KAVACH_DB.RULES TO ROLE KAVACH_ANALYST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA KAVACH_DB.RULES TO ROLE KAVACH_ANALYST;
GRANT SELECT ON ALL VIEWS IN SCHEMA KAVACH_DB.REF TO ROLE KAVACH_ANALYST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA KAVACH_DB.REF TO ROLE KAVACH_ANALYST;
GRANT SELECT ON ALL VIEWS IN SCHEMA KAVACH_DB.APP TO ROLE KAVACH_ANALYST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA KAVACH_DB.APP TO ROLE KAVACH_ANALYST;
GRANT SELECT ON ALL VIEWS IN SCHEMA KAVACH_DB.AUDIT TO ROLE KAVACH_ANALYST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA KAVACH_DB.AUDIT TO ROLE KAVACH_ANALYST;
GRANT SELECT ON ALL VIEWS IN SCHEMA KAVACH_DB.ML TO ROLE KAVACH_AUDITOR;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA KAVACH_DB.ML TO ROLE KAVACH_AUDITOR;
GRANT SELECT ON ALL VIEWS IN SCHEMA KAVACH_DB.AI TO ROLE KAVACH_AUDITOR;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA KAVACH_DB.AI TO ROLE KAVACH_AUDITOR;
GRANT SELECT ON ALL VIEWS IN SCHEMA KAVACH_DB.CORE TO ROLE KAVACH_AUDITOR;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA KAVACH_DB.CORE TO ROLE KAVACH_AUDITOR;
GRANT SELECT ON ALL VIEWS IN SCHEMA KAVACH_DB.RULES TO ROLE KAVACH_AUDITOR;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA KAVACH_DB.RULES TO ROLE KAVACH_AUDITOR;
GRANT SELECT ON ALL VIEWS IN SCHEMA KAVACH_DB.REF TO ROLE KAVACH_AUDITOR;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA KAVACH_DB.REF TO ROLE KAVACH_AUDITOR;
GRANT SELECT ON ALL VIEWS IN SCHEMA KAVACH_DB.APP TO ROLE KAVACH_AUDITOR;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA KAVACH_DB.APP TO ROLE KAVACH_AUDITOR;
GRANT SELECT ON ALL VIEWS IN SCHEMA KAVACH_DB.AUDIT TO ROLE KAVACH_AUDITOR;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA KAVACH_DB.AUDIT TO ROLE KAVACH_AUDITOR;
GRANT SELECT ON ALL VIEWS IN SCHEMA KAVACH_DB.ML TO ROLE KAVACH_REVIEWER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA KAVACH_DB.ML TO ROLE KAVACH_REVIEWER;
GRANT SELECT ON ALL VIEWS IN SCHEMA KAVACH_DB.AI TO ROLE KAVACH_REVIEWER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA KAVACH_DB.AI TO ROLE KAVACH_REVIEWER;
GRANT SELECT ON ALL VIEWS IN SCHEMA KAVACH_DB.CORE TO ROLE KAVACH_REVIEWER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA KAVACH_DB.CORE TO ROLE KAVACH_REVIEWER;
GRANT SELECT ON ALL VIEWS IN SCHEMA KAVACH_DB.RULES TO ROLE KAVACH_REVIEWER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA KAVACH_DB.RULES TO ROLE KAVACH_REVIEWER;
GRANT SELECT ON ALL VIEWS IN SCHEMA KAVACH_DB.REF TO ROLE KAVACH_REVIEWER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA KAVACH_DB.REF TO ROLE KAVACH_REVIEWER;
GRANT SELECT ON ALL VIEWS IN SCHEMA KAVACH_DB.APP TO ROLE KAVACH_REVIEWER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA KAVACH_DB.APP TO ROLE KAVACH_REVIEWER;
GRANT SELECT ON ALL VIEWS IN SCHEMA KAVACH_DB.AUDIT TO ROLE KAVACH_REVIEWER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA KAVACH_DB.AUDIT TO ROLE KAVACH_REVIEWER;
